### ISSUE TITLE
grabber.py

### ISSUE THREAD

**Issue by b-Istiak-s** [TermuxHackz/whatsapp-hacking#5]
```
Traceback (most recent call last):
  File "/home/istiak/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/istiak/HackingProjects/whatsapp-hacking/grabber.py", line 10, in <module>
    browser = webdriver.Firefox()  # init browser
  File "/home/istiak/.local/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/home/istiak/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 79, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
```

I think this isn't issue of code. But, I am not sure how to solve it.

**Comment by TermuxHackz** [comment]
Thanks for reaching out to me
The issues is caused as a result of web driver missing from your browser as
you need to download it so the script would work as intended to

**Comment by Trinadhnaidu** [comment]
![IMG_20210808_100525.jpg](https://user-images.githubusercontent.com/78342315/128620914-570c8477-f64c-4049-b3cf-36671a90e40b.jpg)

**Comment by Trinadhnaidu** [comment]
Sir can you tell me what it is coming like this

**Comment by Alex-145** [comment]
![image](https://user-images.githubusercontent.com/48441459/169474365-8cbdbc35-4a97-4d1c-a617-a21ae38b1ef5.png)

can you help me?, please

**Comment by Trinadhnaidu** [comment]
In termux i don't know buddy ..
whether it will work or not in Linux it works for me...
